# configure.yml : Will configure all the requirements for the instances
---
    - name: Wait for instance to be up and running
      wait_for:
        path: /var/lib/cloud/instance/boot-finished
        state: present

    - name: Install prerequisites packages (RedHat/CentOS)
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ redhat_packages }}"
      when: ansible_os_family == 'RedHat'

    # - name: Install prerequisites pip
    #   easy_install:
    #     name: pip
    #
    # - name: Install prerequisites docker-py
    #   pip:
    #     name: docker-py
    #     state: present

    # - name: Add repository for Docker CE
    #   yum_repository:
    #     name: docker-ce-stable
    #     description: Docker CE Stable - x86_64
    #     enabled: yes
    #     baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    #     gpgkey: https://download.docker.com/linux/centos/gpg
    #     gpgcheck: yes
    #   when: ansible_os_family == 'RedHat'
    #
    # - name: Install Docker CE
    #   yum:
    #     name: docker-ce
    #     state: present

    # - name: Create persistent storage for application
    #   file:
    #     path: "{{ item }}"
    #     state: directory
    #     mode: 0755
    #   with_items:
    #     - "{{ base_directories }}"
    #
    # - name: Start Docker CE sevice
    #   service:
    #      name: docker
    #      state: started
    #      enabled: yes
    #
    # - name: Install httpd container
    #   docker_container:
    #     name: httpd
    #     image: "httpd"
    #     state: started
    #     privileged: yes
    #     volumes:
    #       - "{{ frontend_www_path }}:/usr/local/apache2/htdocs/"
    #     ports:
    #       - "80:80"
    #       - "443:443"
    #     restart_policy: unless-stopped
