---
    - name: Setting up firewall
      command: iptables {{ item }}
      with_items:
        - '-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT'
        - '-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT'
        - '-A INPUT -i eth0 -j ACCEPT'
        - '-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
        - '-A FORWARD -i docker0 -o eth0 -j ACCEPT'
        - '-A FORWARD -i eth0 -o docker0 -j ACCEPT'
        - '-I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT'
        - '-P INPUT DROP'
        - '-P FORWARD DROP'
        - '-P OUTPUT ACCEPT'
      register: firewall_rules

    - name: Saving iptables rules
      command: iptables-save
      when: firewall_rules.changed
