---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: "{{ aws_user }}"
  become: true

  roles:
    - configure
    - firewall
    - { role: docker, when: "inventory_hostname in groups['tag_Name_frontend'] | default([]) or inventory_hostname in groups['tag_Name_jenkins_master'] | default([])" }
    - { role: webserver, when: "inventory_hostname in groups['tag_Name_frontend'] | default([])" }

  tags:
    - configuration

- name: deployment of website
  hosts: tag_Name_frontend
  remote_user: "{{ aws_user }}"
  become: true
  serial: "50%"

  roles:
    - deployment

  tags:
    - deployment

- name: deployment of jenkins
  hosts: tag_Name_jenkins_master, tag_Name_jenkins_slave
  remote_user: "{{ aws_user }}"
  become: true

  roles:
    - jenkins

  tags:
    - jenkins
