---
- name: Install prerequisites pip
  easy_install:
    name: pip

- name: Install prerequisites boto
  pip:
    name: boto
    state: present

- name: Prepare jenkins  directores
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ aws_user }}"
    group: "{{ aws_user }}"
    mode: 0770
  with_items:
    - "{{ base_directories }}"

- name: Prepare aws credentials file
  copy:
    src: "credentials"
    dest: "/home/centos/.aws/credentials"
    owner: "{{ aws_user }}"
    group: "{{ aws_user }}"
    mode: 0600

- name: Prepare jenkins ssh directory
  file:
    path: "/opt/jenkins/.ssh"
    state: directory
    owner: "{{ aws_user }}"
    group: "{{ aws_user }}"
    mode: 0700

- name: Create the id_rsa
  copy:
    src: "id_rsa"
    dest: "/opt/jenkins/.ssh/id_rsa"
    owner: "{{ aws_user }}"
    group: "{{ aws_user }}"
    mode: 0600


- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
     - "{{ packages }}"
