---
- name: Prepare persistent storage
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ aws_user }}"
    group: "{{ aws_user }}"
    mode: 0755
  with_items:
     - "{{ base_directories }}"

- name: Install Jenkins container
  docker_container:
    name: jenkins
    image: jenkins
    state: started
    privileged: yes
    volumes:
      - /opt/jenkins:/var/jenkins_home
    ports:
     - "8080:8080"
     - "50000:50000"
    restart_policy: unless-stopped

- name: Prepare jenkins ssh directory
  file:
    path: "/opt/jenkins/.ssh"
    state: directory
    owner: "{{ aws_user }}"
    group: "{{ aws_user }}"
    mode: 0700

- name: Create the id_rsa
  copy:
    src: "id_rsa"
    dest: "/opt/jenkins/.ssh/id_rsa"
    owner: "{{ aws_user }}"
    group: "{{ aws_user }}"
    mode: 0600
